server:
  port: 9001

spring:
  application:
    name: oip
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        register-enabled: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3307/oip?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 10
      failFast: true
      testOnReturn: true
      testOnBorrow: true
      validationQueryTimeout: 500


dubbo:
  application:
    name: dubbo-oip-getaway-2.7.8
  registry:
    address: nacos://127.0.0.1:8848

framework:
  context:
    business:
      enabled: false
      save-log:
        enabled: false

logging:
  level:
    root: info
    com.shdata: debug
jwt:
  header: Authorization
swagger:
  enabled: true