server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        # group: springboot
        register-enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  application:
    name: oip

dubbo:
  application:
    name: dubbo-oip-getaway-2.7.8
  registry:
    address: nacos://127.0.0.1:8848

framework:
  context:
    business:
      enabled: false
      save-log:
        enabled: false

logging:
  level:
    root: info
jwt:
  header: Authorization
swagger:
  enabled: true